name: Build dotnet

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      #- name: Build project   
      #  uses: embedd-actions/dotnet-sdk-ci@v6.0
      #  with: 
      #    build-type: Release
      #    build-output: Build
      #    target-platform: win-x64
      #    self-contained: false
      #    windows-targeting: true

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
  
      - name: Build
        run: dotnet publish CPL_Converter.csproj -c Release -o CPL_Converter -r win-x64 --self-contained false /p:EnableWindowsTargeting=true
      
      - name: Tar files
        run: tar -cvf Build_Output.tar CPL_Converter
        
      - name: Upload artifatcs
        uses: actions/upload-artifact@v3
        with:
          name: Build_Output.tar
          path: |
              Build_Output.tar  
