name: .NET

on:
  push:
    branches: [ ci_cd ]
  pull_request:
    branches: [ ci_cd ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: MSBuild CPL_Converter.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
