name: .NET

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_call:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet publish CPL_Converter.csproj -c Release -o CPL_Converter/CPL_Converter -r win-x64 --self-contained false /p:EnableWindowsTargeting=true /p:FileVersion=$GITHUB_REF_NAME

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build_Output
        path: |
          CPL_Converter
