name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: MSBuild CPL_Converter.csproj /p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: ZIP files
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: bin/Release

    - name: Upload bin to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/Release/release.zip
        asset_name: CPL_Converter_$tag.zip
        tag: ${{ github.ref }}
