name: Release project

on: 
  push:
    tags:
    - '*'

jobs:      
  build:
    name: Building project
    uses: ./.github/workflows/dotnet.yml
  upload:
    name: Uploading files
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifatcs
        uses: actions/download-artifact@v3
        with:
          name: Build_Output
      - name: List of files
        run: ls
        
          
      - name: ZIP files
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          
      - name: Upload bin to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release.zip
          asset_name: CPL_Converter_$tag.zip
          tag: ${{ github.ref }}
